image: newtnewtnewt/dunnnm2finalprojectimage
 
workflow:
   rules:
         - if: $CI_MERGE_REQUEST_ID
         - if: $CI_COMMIT_BRANCH == 'webprod'
 
stages:
         - deploy
 
distribute_html:
          tags:
                  - aws-tag
          stage: deploy
          script:
                 - echo "user=${GITLAB_USER_LOGIN}"
                 - echo "Configure SSH-AGENT"
                 - 'which ssh-agent || ( apt-get update -y && apt-get install  openssh-client -y )'
                 - eval $(ssh-agent -s)
                 - ssh-add <(echo "$SSH_PRIVATE_KEY")
                 - mkdir -p ~/.ssh
                 - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
                 - cp /GenerateIndexFile .
                 - ./GenerateIndexFile
                 - scp -r * ubuntu@54.147.47.16:/var/www/html
                 - scp -r * ubuntu@35.175.174.212:/var/www/html
                 - scp -r * ubuntu@54.235.34.139:/var/www/html
                 - scp -r * ubuntu@3.80.61.173:/var/www/html
                 - tidy "five.html"
                 - tidy "four.html"
                 - tidy "one.html"
                 - tidy "three.html"
                 - tidy "two.html"
                 - tidy "index.html"
