#!/bin/bash
echo "image: ubuntu:20.04" > .gitlab-ci.yml
echo " " >> .gitlab-ci.yml
echo "workflow:" >> .gitlab-ci.yml
echo "   rules:" >> .gitlab-ci.yml
echo "         - if: \$CI_MERGE_REQUEST_ID" >> .gitlab-ci.yml
echo "         - if: \$CI_COMMIT_BRANCH == 'webprod'" >> .gitlab-ci.yml
echo " " >> .gitlab-ci.yml
echo "stages:" >> .gitlab-ci.yml
echo "         - deploy" >> .gitlab-ci.yml
echo " " >> .gitlab-ci.yml
echo "before_script:" >> .gitlab-ci.yml
echo "         - apt-get update" >> .gitlab-ci.yml
echo "         - apt-get -y install sshpass" >> .gitlab-ci.yml
echo "distribute_html:" >> .gitlab-ci.yml
echo "          tags:" >> .gitlab-ci.yml
echo "                  - aws-tag" >> .gitlab-ci.yml
echo "          stage: deploy" >> .gitlab-ci.yml
echo "          script:" >> .gitlab-ci.yml
echo "                 - echo \"user=\${GITLAB_USER_LOGIN}\"" >> .gitlab-ci.yml
echo "                 - echo \"Configure SSH-AGENT\"" >> .gitlab-ci.yml
echo "                 - 'which ssh-agent || ( apt-get update -y && apt-get install  openssh-client -y )'" >> .gitlab-ci.yml
echo "                 - eval \$(ssh-agent -s)" >> .gitlab-ci.yml
echo "                 - ssh-add <(echo "\"\$SSH_PRIVATE_KEY\"")" >> .gitlab-ci.yml
echo "                 - mkdir -p ~/.ssh" >> .gitlab-ci.yml
echo "                 - '[[ -f /.dockerenv ]] && echo -e "Host *\\n\\tStrictHostKeyChecking no\\n\\n" > ~/.ssh/config'" >> .gitlab-ci.yml
publicIPs=$(aws ec2 describe-instances --filter Name=instance.group-id,Values=sg-015a1e18e5c69bdd1 --query "Reservations[*].Instances[*].PublicIpAddress" --output=text | sed -E 's/[[:space:]]+/\n/g'
)
allfiles=$(find /home/dunnnm2/cse470g/devops-1-dunnnm2/FinalProject1/webfiles/ -type f | tr '\n' ' ')
finaladdreses=""
for i in $allfiles; do
	finaladdresses="${finaladdresses}dunnnm2@ceclnx01.cec.miamioh.edu:$i "
done
for i in $publicIPs; do
	echo "                 - script -qc \"sshpass -p \"\$CEC_PASSWORD\" scp $finaladdresses .\" /dev/null" >> .gitlab-ci.yml
	echo "                 - script -qc \"sshpass -p \"\$CEC_PASSWORD\" scp * ubuntu@$i:/var/www/html\" /dev/null" >> .gitlab-ci.yml
done
cp .gitlab-ci.yml ..
