#!/bin/bash
allroothtmls=$(ls *\.html)
echo "<!DOCTYPE HTML>" > index.html
echo "  <html>" >> index.html
echo "          <head>" >> index.html
echo "                  <title>Index</title>" >> index.html
echo "          </head>" >> index.html
echo "          <body>" >> index.html
echo "                  <h1> Welcome to the index page </h1>" >> index.html
for i in $allroothtmls; do
echo "                  <a href="$i">A Link to $i</a>" >> index.html
echo "                  <br />" >> index.html
done
echo "          </body>" >> index.html
echo "  </html>" >> index.html
