# Name: Noah Dunn
# Professor: Dr. Scott Campbell
# Date: 9/24/2020
# Class: CSE570J
# Assignment: GitLab CI/CD


image: ubuntu:18.04

workflow:
  rules:
         - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge req uest context
         - if: $CI_COMMIT_BRANCH == 'master'

stages:
        - deploy

before_script:
        - apt-get update
        - apt-get -y install wget
        - apt-get -y install sshpass
dunnnm2_test:
        tags:
                - aws-tag
        stage: deploy
        script:
                - echo "user=${GITLAB_USER_LOGIN}"
                - echo "Retrieving Dr. Campbell's Program"
                - wget http://ceclnx01.cec.miamioh.edu/~campbest/add
                - echo "2,4,6" > testinput.csv
                - chmod u+x add
                - echo "Beginning Execution of Add Program"
                - ./add
                - echo "File saved testresult.txt"
                - cat testresult.txt
                - 'which ssh-agent || ( apt-get update -y && apt-get install  openssh-client -y )'
                # Run ssh-agent (inside the build environment)
                - eval $(ssh-agent -s)
                # Add the SSH key stored in SSH_PRIVATE_KEY variable to the a gent store
                - ssh-add <(echo "$SSH_PRIVATE_KEY")
                - mkdir -p ~/.ssh
                - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
                - sshpass -p "$CEC_PASSWORD" scp testresult.txt dunnnm2@cecln x01.cec.miamiOH.edu:/home/dunnnm2