version: '3.3'
services:
   db:
     container_name: dunnnm2-gerardnt-db
     image: mysql:5.7
     volumes:
       - db_data_dunnnm2_gerardnt:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress-dunnnm2-gerardnt
       MYSQL_USER: root
       MYSQL_PASSWORD: wordpress
     restart: always

   wordpress1:
     container_name: dunnnm2-gerardnt-wordpress1
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
       WORDPRESS_DB_NAME: wordpress1-dunnnm2-gerardnt
       WORDPRESS_CONFIG_EXTRA: |  
         define('WP_HOME', "http://docker.csi.miamiOH.edu:5026/site1/");
         define('WP_SITEURL', "http://docker.csi.miamiOH.edu:5026/site1/");
          
   wordpress2:
     container_name: dunnnm2-gerardnt-wordpress2
     depends_on:
       - db
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: somewordpress
       WORDPRESS_DB_NAME: wordpress2-dunnnm2-gerardnt
       WORDPRESS_CONFIG_EXTRA: |
               define('WP_HOME', "http://docker.csi.miamiOH.edu:5026/site2/");
               define('WP_SITEURL', "http://docker.csi.miamiOH.edu:5026/site2/");

   nginx:
     container_name: dunnnm2-gerardnt-nginxrp
     build: ./nginx
     ports:
      - "5026:80"
     depends_on:
      - db
      - wordpress1
      - wordpress2

volumes:
    db_data_dunnnm2_gerardnt: {}
