SELECT * FROM information_schema.TABLES
SELECT * FROM information_schema.COLUMNS


SELECT INFORMATION_SCHEMA.TABLES.TABLE_NAME, INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
LEFT JOIN INFORMATION_SCHEMA.TABLES 
ON INFORMATION_SCHEMA.TABLES.TABLE_NAME = INFORMATION_SCHEMA.COLUMNS.TABLE_NAME
WHERE INFORMATION_SCHEMA.TABLES.TABLE_TYPE = 'BASE TABLE' AND
INFORMATION_SCHEMA.COLUMNS.IS_NULLABLE = 'YES' 
AND INFORMATION_SCHEMA.COLUMNS.DATA_TYPE = 'int' 